### ISSUE TITLE
如何运行呢？

### ISSUE THREAD

**Issue by ifenr** [Moekr/sword#1]
想尝试搭建使用，却不知道该如何使用，总是报错，烦请指导。

**Comment by ifenr** [comment]
Centos 下无法运行么？

**Comment by Moekr** [comment]
> 想尝试搭建使用，却不知道该如何使用，总是报错，烦请指导。

可以贴一下报错内容吗？

**Comment by ifenr** [comment]
![tim 20181102102950](https://user-images.githubusercontent.com/13554721/47890551-50f6ba00-de8a-11e8-8355-0a480b254d2f.png)
按照配置路径，我将output文件cp到了/opt/sword目录下

**Comment by Moekr** [comment]
> ![tim 20181102102950](https://user-images.githubusercontent.com/13554721/47890551-50f6ba00-de8a-11e8-8355-0a480b254d2f.png)
> 按照配置路径，我将output文件cp到了/opt/sword目录下

这个是第一次启动的时候没有本地数据文件才报的错，没有问题，等待保存一次数据后再启动时就不会有这个错误了
目前是每分钟保存一次数据到本地文件，路径为-d设定的目录下的sword.json.gz，每小时保留一次备份数据，路径为-d设定的目录下的sword-[时间戳].json.gz

**Comment by ifenr** [comment]
已经ok了，我修改监听0.0.0.0:1024,就正常了。谢谢
另咨询一下，是否会像smartping一样开发后台添加页面呢？

**Comment by Moekr** [comment]
> 已经ok了，我修改监听0.0.0.0:1024,就正常了。谢谢
> 另咨询一下，是否会像smartping一样开发后台添加页面呢？

web后台的话，个人精力有限，短期内不会考虑，另外这种玩具还是keep it simple & stupid比较好嘛

**Comment by ifenr** [comment]
非常感谢你的分享！
注册服务那里，不知道运行在Centos 6上面是否需要修改？

**Comment by ifenr** [comment]
运行了很长时间，为什么web上面数据一直未没出来呢？

**Comment by Moekr** [comment]
> 非常感谢你的分享！
> 注册服务那里，不知道运行在Centos 6上面是否需要修改？

注册服务那个是适用于systemd的，据我所知Centos6不支持systemd，可能需要使用别的办法

> 运行了很长时间，为什么web上面数据一直未没出来呢？

有启动客户端节点吗？服务端节点只负责接收、存储和展示数据，需要有客户端节点配合进行数据采集

**Comment by ifenr** [comment]
客户端可否在内网环境Windows 下执行？
能否帮忙打包一个exe？

**Comment by Moekr** [comment]
> 客户端可否在内网环境Windows 下执行？
> 能否帮忙打包一个exe？

[sword-windows-amd64.tar.gz](https://ci.moekr.com/job/sword/lastSuccessfulBuild/artifact/src/github.com/Moekr/sword/sword-windows-amd64.tar.gz)
按理来说服务端和客户端之间以及客户端和被监测目标之间能够连通就可以工作

**Comment by ifenr** [comment]
是否可以将监测数据导出成cvs或者写入mysql呢？

**Comment by Moekr** [comment]
> 是否可以将监测数据导出成cvs或者写入mysql呢？

目前只有gzip压缩的json文件，不支持csv或者数据库

**Comment by ifenr** [comment]
烦请查收邮件并反馈一个联系方式。
